[package]
name = "ysos_fwsh"
version.workspace = true
edition.workspace = true

[dependencies]
lib = { workspace = true }
chrono = { workspace = true }
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }